---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudstack-db-properties
  namespace: cloudstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudstack-manager
  namespace: cloudstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudstack-manager
  template:
    metadata:
      labels:
        app: cloudstack-manager
    spec:
      initContainers:
        - name: cloudstack-db-setup
          image: rudester/cloudstack-controller:v0.1.0-rc2
          command: ["cloudstack-setup-databases", "cloud:foobar@mysql-primary-headless.mysql", "--deploy-as=root:foobar"]
          volumeMounts:
            - name: cloudstack-db-properties
              mountPath: "/etc/cloudstack/management"
      containers:
        - name: cloudstack-manager
          image: rudester/cloudstack-controller:v0.1.0-rc2
          command: [ "cloudstack-setup-management" ]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cloudstack-db-properties
              mountPath: "/etc/cloudstack/management"
      volumes:
        - name: cloudstack-db-properties
          persistentVolumeClaim:
            claimName: cloudstack-db-properties

---

apiVersion: v1
kind: Service
metadata:
  name: cloudstack-manager-service
  namespace: cloudstack
spec:
  type: NodePort
  selector:
    app: cloudstack-manager
  ports:
    - port: 8080
      nodePort: 30808
      protocol: TCP
